In [1]:
#Numpy - Numerical Python 

In [2]:
import numpy as np

In [3]:
np.__version__   #checking version 

'1.23.5'

In [4]:
#list to array conversion

In [8]:
list1 = [1,2,3,4,5,6,'Thala',8,9,10]
print(f'List : {list1}\nType :{type(list1)}\n')
arr = np.array(list1)
print(f'Array : {arr}\nType : {type(arr)}')

List : [1, 2, 3, 4, 5, 6, 'Thala', 8, 9, 10]
Type :<class 'list'>

Array : ['1' '2' '3' '4' '5' '6' 'Thala' '8' '9' '10']
Type : <class 'numpy.ndarray'>


In [11]:
#type of an array 

type(arr)

numpy.ndarray

In [16]:
#Finding the dimentions of an array

print(f'Its an " {arr.ndim}d " array.')

Its an " 1d " array.


In [17]:
#can we create 2D arrya ? Yes 

In [18]:
arr1 = np.array([[1,2,3,4,5], [6,7,8,9,0]])
arr1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [20]:
print(f'Its an " {arr1.ndim}d " array.')

Its an " 2d " array.


In [21]:
#Matrix

In [23]:
np.matrix([1,2,3,4,5]) #matrix is a specialized arrya i.e 2D array. It will not be a 3D array.

matrix([[1, 2, 3, 4, 5]])

In [24]:
# ******** Ways to converting into Matrix ********

In [ ]:
# Using > np.array()
arr1 = np.array([[1,2,3,4,5], [6,7,8,9,0]])
arr1

In [ ]:
#whther its an array or not.

In [28]:
#Using > np.asarray()
l = [1,2,3]
print(f'List : {l}\t Type {type(l)}')
np.asarray(l)

List : [1, 2, 3]	 Type <class 'list'>


array([1, 2, 3])

In [ ]:
#If its not an array.

In [40]:
#Using > np.asanyarray(l)
l = [1,2,3]
np.asanyarray(l)

array([1, 2, 3])

In [30]:
#Converting Tuple into Array

In [31]:
l = ([1,2,3],[4,5,6])
print(f'List : {l}\t Type {type(l)}')
np.array(l)

List : ([1, 2, 3], [4, 5, 6])	 Type <class 'tuple'>


array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
#Shallow & Deep Copy

In [33]:
arr = ([1,2,3,4,5])

arr[0] = 1008

arr

[1008, 2, 3, 4, 5]

In [35]:
#Shallow Copy


#We are refereing the "shallow_arr" -> "arr"
shallow_arr = arr

#making changes in "arr" but not in "shallow_arr"
arr[0] = 108


#still its reflecting the changes made in "arr" into "shallow_arr". This is called "Shallow Copy"
shallow_arr

[108, 2, 3, 4, 5]

In [39]:
#Deep Copy


#We are refereing the "deep_arr" -> "arr"
deep_arr = arr.copy()

#making changes in "arr" but not in "deep_arr". i.e 108 -> 1008
arr[0] = 1008


#But its not reflecting the changes made in "arr" into "deep_arr". This is called "Deep Copy"
deep_arr

[108, 2, 3, 4, 5]

In [41]:
#Multiple ways to generate arrays

In [42]:
#fromfunction()

In [48]:
import numpy as np

# Define a function that takes row and column indices as input and returns their sum
def sum_of_indices(x, y):
    return x + y

# Use numpy.fromfunction() to create the array
array = np.fromfunction(sum_of_indices, (3, 3), dtype=int) #dtype=int > as bydefault their type will be float so.

array


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [45]:
#fromiter() 

In [47]:
#Creating 1-D array from iterable object.
import numpy as np

# Create a list of numbers
numbers_list = [1, 2, 3, 4, 5]

# Use numpy.fromiter() to create an array from the list
array = np.fromiter(numbers_list, dtype=int)

array

array([1, 2, 3, 4, 5])

In [56]:
#arange()

In [57]:
np.arange(1,10, 0.1) # start end difference

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])